### ISSUE TITLE
OpenResty也有一个echo模块，不知有何区别？？

### ISSUE THREAD

**Issue by rabbitLove520** [wujunze/nginx-http-echo-module#4]
[echo](https://github.com/openresty/echo-nginx-module)

**Comment by wujunze** [comment]
OpenResty的echo功能完善  指令更多  推荐生产环境用
我这个echo模块  代码简单清晰   功能也简单  适合学习Nginx模块开发用   不推荐在生成环境使用

**Comment by rabbitLove520** [comment]
soga
